# Freepik Plugin Configuration
# ============================
# Get your FREE API key at: https://www.freepik.com/developers/dashboard
# (Signing up gives you $5 in free credits)
#
# Replace YOUR_KEY_HERE with your actual API key:

api_key=FPSXbab0c76d0f77886d48111ed15c7d41dc
https://img.freepik.com/free-photo/vertical-shot-curvy-road-forest-covered-yellowing-trees-dried-leaves-autum_181624-58749.jpg?uid=R238304597&ga=GA1.1.963910175.1775369195&semt=ais_incoming&w=740&q=80
