$primary_paletteKeyColor = ad625f
$secondary_paletteKeyColor = 916e6c
$tertiary_paletteKeyColor = 8e7344
$neutral_paletteKeyColor = 827473
$neutral_variant_paletteKeyColor = 857372
$background = 1a1111
$onBackground = f1dedd
$surface = 1a1111
$surfaceDim = 1a1111
$surfaceBright = 423736
$surfaceContainerLowest = 140c0c
$surfaceContainerLow = 231919
$surfaceContainer = 271d1d
$surfaceContainerHigh = 322827
$surfaceContainerHighest = 3d3231
$onSurface = f1dedd
$surfaceVariant = 534342
$onSurfaceVariant = d8c1c0
$inverseSurface = f1dedd
$inverseOnSurface = 382e2d
$outline = a08c8b
$outlineVariant = 534342
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb3af
$primary = ffb3af
$onPrimary = 571d1d
$primaryContainer = 733331
$onPrimaryContainer = ffdad7
$inversePrimary = 904a47
$secondary = e7bdba
$onSecondary = 442928
$secondaryContainer = 5d3f3d
$onSecondaryContainer = ffdad7
$tertiary = e2c28c
$onTertiary = 402d05
$tertiaryContainer = a98d5b
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdad7
$primaryFixedDim = ffb3af
$onPrimaryFixed = 3b080a
$onPrimaryFixedVariant = 733331
$secondaryFixed = ffdad7
$secondaryFixedDim = e7bdba
$onSecondaryFixed = 2c1514
$onSecondaryFixedVariant = 5d3f3d
$tertiaryFixed = ffdea8
$tertiaryFixedDim = e2c28c
$onTertiaryFixed = 271900
$onTertiaryFixedVariant = 594319
$term0 = 353434
$term1 = ff5453
$term2 = ffbda5
$term3 = ffdfd7
$term4 = b9ab66
$term5 = f08f94
$term6 = ffba93
$term7 = f0d2cb
$term8 = b49e99
$term9 = ff857e
$term10 = ffd4c5
$term11 = fff1ee
$term12 = dcbc93
$term13 = ffa8a9
$term14 = ffd2bd
$term15 = ffffff
$rosewater = ffeeec
$flamingo = ffd9d7
$pink = ffd2d5
$mauve = ffa8b9
$red = ff9699
$maroon = f9aaa9
$peach = ffbeb4
$yellow = ffede9
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa1c3
$lavender = ffbacd
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cd5b73
$kvisitedSelection = cd5b72
$knegative = ec5256
$knegativeSelection = ec5255
$kneutral = ff8978
$kneutralSelection = ff8978
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f1dedd
$subtext1 = d8c1c0
$subtext0 = a08c8b
$overlay2 = 8c7a79
$overlay1 = 776766
$overlay0 = 655655
$surface2 = 534544
$surface1 = 413434
$surface0 = 2d2222
$base = 1a1111
$mantle = 1a1111
$crust = 191010
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
