$background = 0c0e12
$onBackground = e2e5ef
$surface = 0c0e12
$surfaceDim = 0c0e12
$surfaceBright = 282c34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 111318
$surfaceContainer = 161a1f
$surfaceContainerHigh = 1c2026
$surfaceContainerHighest = 22262d
$onSurface = e2e5ef
$surfaceVariant = 22262d
$onSurfaceVariant = a7abb4
$outline = 71757e
$outlineVariant = 444850
$inverseSurface = f9f9fe
$inverseOnSurface = 535559
$shadow = 000000
$scrim = 000000
$surfaceTint = b1c8ec
$primary = b1c8ec
$primaryDim = a4bade
$onPrimary = 2b415f
$primaryContainer = 3d5472
$onPrimaryContainer = d5e4ff
$inversePrimary = 4a6080
$primaryFixed = c2d9fe
$primaryFixedDim = b4cbef
$onPrimaryFixed = 223956
$onPrimaryFixedVariant = 3f5574
$secondary = bcc7db
$secondaryDim = aeb9cd
$onSecondary = 364151
$secondaryContainer = 313c4c
$onSecondaryContainer = b5c0d4
$secondaryFixed = d8e3f8
$secondaryFixedDim = cad5ea
$onSecondaryFixed = 354050
$onSecondaryFixedVariant = 515c6e
$tertiary = e5daff
$tertiaryDim = d8cafb
$onTertiary = 544a73
$tertiaryContainer = d8cafb
$onTertiaryContainer = 4b416a
$tertiaryFixed = d8cafb
$tertiaryFixedDim = cabded
$onTertiaryFixed = 382e55
$onTertiaryFixedVariant = 554a74
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 627899
$secondaryPaletteKeyColor = 6d788a
$tertiaryPaletteKeyColor = 7c719d
$neutralPaletteKeyColor = 76777c
$neutralVariantPaletteKeyColor = 737780
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 627899
$secondary_paletteKeyColor = 6d788a
$tertiary_paletteKeyColor = 7c719d
$neutral_paletteKeyColor = 76777c
$neutral_variant_paletteKeyColor = 737780
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 88aed2
$term5 = 99a6ef
$term6 = 92d1f8
$term7 = ccdcd6
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = acc4d8
$term13 = b3bbf9
$term14 = b3e1ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = e1e0f5
$pink = d4dbff
$mauve = a6bfff
$red = a3afff
$maroon = b5bbf1
$peach = e0c2f9
$yellow = d0f9f4
$green = bfe5ff
$teal = c5e3ff
$sky = c0deff
$sapphire = 9ecbff
$blue = 93bfff
$lavender = b3cdff
$klink = 4e8acc
$klinkSelection = 4f8acc
$kvisited = 557ddc
$kvisitedSelection = 567ddd
$knegative = 6d7bff
$knegativeSelection = 6e7aff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b5f7
$kpositiveSelection = 00b5f8
$text = e2e5ef
$subtext1 = a7abb4
$subtext0 = 71757e
$overlay2 = 63666e
$overlay1 = 54575e
$overlay0 = 46494f
$surface2 = 383b41
$surface1 = 2a2d32
$surface0 = 1b1d22
$base = 0c0e12
$mantle = 0c0e12
$crust = 0b0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
