$background = 120d10
$onBackground = f2e1ea
$surface = 120d10
$surfaceDim = 120d10
$surfaceBright = 332930
$surfaceContainerLowest = 000000
$surfaceContainerLow = 181116
$surfaceContainer = 1f171c
$surfaceContainerHigh = 251d23
$surfaceContainerHighest = 2d2329
$onSurface = f2e1ea
$surfaceVariant = 2d2329
$onSurfaceVariant = b6a7af
$outline = 7f7279
$outlineVariant = 50454c
$inverseSurface = fff7f9
$inverseOnSurface = 5a5357
$shadow = 000000
$scrim = 000000
$surfaceTint = e8b9d9
$primary = e8b9d9
$primaryDim = daabcb
$onPrimary = 58354f
$primaryContainer = 6c4762
$onPrimaryContainer = ffd8f1
$inversePrimary = 79536f
$primaryFixed = fac9ea
$primaryFixedDim = ebbbdc
$onPrimaryFixed = 4f2d47
$onPrimaryFixedVariant = 6e4864
$secondary = dcbed1
$secondaryDim = cdb1c3
$onSecondary = 4f3a49
$secondaryContainer = 4a3544
$onSecondaryContainer = d4b7c9
$secondaryFixed = f9daed
$secondaryFixedDim = eaccdf
$onSecondaryFixed = 4e3948
$onSecondaryFixedVariant = 6c5564
$tertiary = f0dfff
$tertiaryDim = e5ceff
$onTertiary = 5d4c74
$tertiaryContainer = e5ceff
$onTertiaryContainer = 55436b
$tertiaryFixed = e5ceff
$tertiaryFixedDim = d7c0f0
$onTertiaryFixed = 413057
$onTertiaryFixedVariant = 5e4c75
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 946b88
$secondaryPaletteKeyColor = 897080
$tertiaryPaletteKeyColor = 826f9a
$neutralPaletteKeyColor = 7d7579
$neutralVariantPaletteKeyColor = 81737b
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 946b88
$secondary_paletteKeyColor = 897080
$tertiary_paletteKeyColor = 826f9a
$neutral_paletteKeyColor = 7d7579
$neutral_variant_paletteKeyColor = 81737b
$term0 = 353434
$term1 = fa46bb
$term2 = ffbac2
$term3 = ffdde6
$term4 = b3a2d5
$term5 = df92c6
$term6 = ffba93
$term7 = ecd2d8
$term8 = b19ea3
$term9 = ff7bc7
$term10 = ffd2d5
$term11 = fff1f3
$term12 = babfdd
$term13 = efaad4
$term14 = ffd1c0
$term15 = ffffff
$rosewater = feedf3
$flamingo = f8dae7
$pink = ffcfef
$mauve = f2a8ea
$red = f197d1
$maroon = ebacd0
$peach = ffbad6
$yellow = ffedf0
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = e6b6fd
$blue = e4a7f1
$lavender = f2baf4
$klink = a972be
$klinkSelection = a972be
$kvisited = b860af
$kvisitedSelection = b860af
$knegative = de51af
$knegativeSelection = de51af
$kneutral = ff80be
$kneutralSelection = ff80be
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f2e1ea
$subtext1 = b6a7af
$subtext0 = 7f7279
$overlay2 = 6f646a
$overlay1 = 5f545a
$overlay0 = 50474c
$surface2 = 41393d
$surface1 = 322b2f
$surface0 = 221c1f
$base = 120d10
$mantle = 120d10
$crust = 110c0f
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
