$background = 151311
$onBackground = e7e1dd
$surface = 151311
$surfaceDim = 151311
$surfaceBright = 3b3936
$surfaceContainerLowest = 100e0c
$surfaceContainerLow = 1d1b19
$surfaceContainer = 211f1d
$surfaceContainerHigh = 2c2a27
$surfaceContainerHighest = 373431
$onSurface = e7e1dd
$surfaceVariant = 4c463c
$onSurfaceVariant = cfc5b8
$outline = 989084
$outlineVariant = 4c463c
$inverseSurface = e7e1dd
$inverseOnSurface = 32302d
$shadow = 000000
$scrim = 000000
$surfaceTint = dac49f
$primary = e2cba6
$primaryDim = fde5be
$onPrimary = 3c2e14
$primaryContainer = c5b08c
$onPrimaryContainer = 524327
$inversePrimary = 6d5c3e
$primaryFixed = f7e0b9
$primaryFixedDim = dac49f
$onPrimaryFixed = 251a03
$onPrimaryFixedVariant = 544528
$secondary = d1c5b3
$secondaryDim = eee1ce
$onSecondary = 372f23
$secondaryContainer = 4e4638
$onSecondaryContainer = bfb4a2
$secondaryFixed = eee1ce
$secondaryFixedDim = d1c5b3
$onSecondaryFixed = 211b0f
$onSecondaryFixedVariant = 4e4638
$tertiary = c9d3b1
$tertiaryDim = ebf5d2
$onTertiary = 2b331c
$tertiaryContainer = adb797
$onTertiaryContainer = 3f482f
$tertiaryFixed = dde7c4
$tertiaryFixedDim = c1cbaa
$onTertiaryFixed = 161e09
$onTertiaryFixedVariant = 414a31
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 877555
$secondaryPaletteKeyColor = 807667
$tertiaryPaletteKeyColor = adb797
$neutralPaletteKeyColor = 7a7672
$neutralVariantPaletteKeyColor = 7e766b
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 877555
$secondary_paletteKeyColor = 807667
$tertiary_paletteKeyColor = adb797
$neutral_paletteKeyColor = 7a7672
$neutral_variant_paletteKeyColor = 7e766b
$term0 = 353433
$term1 = c88200
$term2 = f6c642
$term3 = ffe2b2
$term4 = b3ad69
$term5 = e29b4d
$term6 = e0c86e
$term7 = e6d6bf
$term8 = aea18f
$term9 = e89800
$term10 = ffd97c
$term11 = fff2e1
$term12 = cbc194
$term13 = f1b36d
$term14 = f7d974
$term15 = ffffff
$rosewater = feefe0
$flamingo = f9ddc1
$pink = ffd5b2
$mauve = ffad7f
$red = f1a346
$maroon = ebb475
$peach = f5c680
$yellow = ffefd7
$green = fbde77
$teal = eee18c
$sky = e1df87
$sapphire = b3d27e
$blue = 75cf9d
$lavender = ffbcbb
$klink = 559652
$klinkSelection = 559652
$kvisited = c36901
$kvisitedSelection = c16a00
$knegative = bf7800
$knegativeSelection = be7900
$kneutral = e69c00
$kneutralSelection = e49c00
$kpositive = c7a700
$kpositiveSelection = c5a800
$text = e7e1dd
$subtext1 = cfc5b8
$subtext0 = 989084
$overlay2 = 847d73
$overlay1 = 706a62
$overlay0 = 5e5952
$surface2 = 4c4842
$surface1 = 3b3733
$surface0 = 282522
$base = 151311
$mantle = 151311
$crust = 141210
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
