# ### Hyprland ###
# Apps
$terminal = foot
$browser = zen-browser
$editor = code
$fileExplorer = nemo

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.8
$workspaceSwipeFingers = 3
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false
$blurVibrancy = 0.2
$blurBrightness = 1.0
$blurNoise = 0.01

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 5
$windowGapsOut = 8
$singleWindowGapsOut = 8

# Window styling
$activeOpacity = 1.0
$inactiveOpacity = 0.9
$windowOpacity = 0.95
$windowRounding = 12
$dimInactive = true
$dimStrength = 0.05
 
$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 10  # In percent
$cursorTheme = Adwaita
$cursorSize = 30

# Alpha variables (Missing in current.conf, defining here for convenience)
$primarye6 = f8b8a0e6
$onSurfaceVariant11 = bca69f11
$backgrounde9 = 130d0ae9
$surfaced4 = 130d0ad4
$secondarye6 = e7beafe6


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Alt, F4

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, N
$MvkbTodo = Super+Alt, N
$kbresizetocenter = Super ,R

# Apps
$kbTerminal = Super, T
$kbBrowser = Super, Q
$kbEditor = Super, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
