animations {
    enabled = true

    # Animation curves
    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = cuzin, 0.27, 0.06, 0.12, 0.9
    bezier = hyprermia, 0.05, 0.9, 0.1, 1.05
    bezier = fluid, 0, 0.5, 0, 1
    bezier = snip, 0.1, 1, 1, 0.1

    # Animation configs
    animation = windows, 1, 3, overshot, slide
    animation = windowsIn, 1, 3, md3_decel, slide
    animation = windowsOut, 1, 3, md3_accel, slide
    animation = windowsMove, 1, 3, md3_standard, slide
    
    animation = layers, 1, 3, md3_decel, slide
    animation = layersIn, 1, 3, cuzin, slide
    animation = layersOut, 1, 3, cuzin, slide
    
    animation = fade, 1, 3, md3_decel
    animation = fadeLayersIn, 1, 3, cuzin
    animation = fadeLayersOut, 1, 3, cuzin
    animation = fadeDim, 1, 3, md3_decel
    
    animation = workspaces, 1, 4, hyprermia, slide
    animation = workspacesIn, 1, 4, hyprermia, slide
    animation = workspacesOut, 1, 4, hyprermia, slide
    
    animation = specialWorkspace, 1, 4, hyprermia, slidefadevert 15%
    
    animation = border, 1, 3, md3_standard
}


