decoration {
    rounding = $windowRounding
    
    active_opacity = $activeOpacity
    inactive_opacity = $inactiveOpacity

    dim_inactive = $dimInactive
    dim_strength = $dimStrength

    blur {
        enabled = $blurEnabled
        xray = $blurXray
        special = $blurSpecialWs
        ignore_opacity = true
        new_optimizations = true
        popups = $blurPopups
        input_methods = $blurInputMethods
        size = $blurSize
        passes = $blurPasses
        vibrancy = $blurVibrancy
        brightness = $blurBrightness
        noise = $blurNoise
    }

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        color = $shadowColour
    }
}

