# Ensure portals and systemd know we are in Wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursors (Syncing Hyprland and GTK)
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Background services
exec-once = mpris-proxy
exec-once = ydotoold --socket-path /tmp/.ydotool_socket
exec-once = xsettingsd
exec-once = ~/.scripts/organise.sh

# UI and Shell Components
exec-once = hyprpm reload
exec-once = caelestia shell -d
exec-once = quickshell -p /home/jay/.config/quickshell/shell.qml
exec-once = sleep 1 && awww-daemon
exec-once = sleep 1 && gammastep
