input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 180
    repeat_rate = 50
    sensitivity = 0.4
    accel_profile = flat
    follow_mouse = 1
    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
        middle_button_emulation = true
        tap-to-click = true
    }
}


binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    no_hardware_cursors = false
}

