plugin = /var/cache/hyprpm/jay/hyprland-plugins/hyprbars.so

plugin { 
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = center current
        gesture_distance = 300
    }
    hyprbars {
        bar_height = 32
        bar_color = rgb($background)
        bar_blur = true

        bar_title_enabled = true
        bar_text_size = 12
        bar_text_font = SF Pro Display Semibold

        bar_text_align = center
        bar_buttons_alignment = left

        bar_padding = 15
        bar_button_padding = 6

        col.text = rgb($secondary) 
        on_double_click = hyprctl dispatch fullscreen 1

        hyprbars-button = rgb(f85656), 15,   , hyprctl dispatch killactive
        hyprbars-button = rgb(f9bc4a), 15,   , ~/.config/hypr/scripts/toggleworkspace.sh
        hyprbars-button = rgb(39c951), 15,   , hyprctl dispatch fullscreen 1
        
    }
}

windowrule = match:float 0, hyprbars:no_bar 1
windowrule = match:float 1, hyprbars:no_bar 1
